### ISSUE TITLE
no output during evaluation

### ISSUE THREAD

**Issue by dqxiu** [YerevaNN/warp#8]
Hi, thanks for your job for the paper and code.
I can train the model smoothly. However, when I run 
```
python -m allennlp predict \
  --silent --use-dataset-reader --cuda-device 0 \
  --batch-size 50 \
  --predictor glue --output-file v0.1/MNLI-m.tsv /data/arp/.aim/H-93ae5ae9 test_matched

```
I'm confused about the parameters on the last line, as well as the data organization, cause the datasets were downloaded automatically to /home/dqx/.cache/huggingface/datasets/glue/mnli/train.arrow，but I'm not clear about the data in tsv format. Are they downloaded manually and just stored under WARP/ ? And how can I evaluate  the model on my own testing data?
If I upload rte.dev as the testing data to WARP/ and run the following command
```
python -m allennlp predict \
  --silent --use-dataset-reader --cuda-device 0 \
  --batch-size 50 \
  --predictor super_glue --output-file test_output.tsv .aim/t-rte  dev.tsv
```
the terminal output will be a list like "[...fixed_cross_validation_79', 'few_wsc.fixed_cross_validation_80', 'few_wsc.fixed_cross_validation_81', 'few_wsc.fixed_cross_validation_82', 'few_wsc.fixed_cross_validation_83', 'few_wsc.fixed_cross_validation_84', 'few_wsc.fixed_cross_validation_85', 'few_wsc.fixed_cross_validation_86', 'few_wsc.fixed_cross_validation_87', 'few_wsc.fixed_cross_validation_88', 'few_wsc.fixed_cross_validation_89', 'few_wsc.fixed_cross_validation_90', 'few_wsc.fixed_cross_validation_91', 'few_wsc.fixed_cross_validation_92', 'few_wsc.fixed_cross_validation_93', 'few_wsc.fixed_cross_validation_94', 'few_wsc.fixed_cross_validation_95', 'few_wsc.fixed_cross_validation_96', 'few_wsc.fixed_cross_validation_97', 'few_wsc.fixed_cross_validation_98', 'few_wsc.fixed_cross_validation_99', 'few_wsc.fixed_cross_validation_100']" but there's nothing in test_output.tsv.

I'm really confused about this, looking forward to your response, thanks😊✨

**Comment by mahnerak** [comment]
Dear @dqxiu,

The dataset name like `test_matched` (including `few_wsc.fixed_cross_validation_94`) serve as an input to `huggingface/datasets` library (https://github.com/huggingface/datasets).
> play with here: https://huggingface.co/datasets/viewer/

Here the `.tsv` (or `.json`) files serve only as output files (used only with `--output-file`) to make them compatible to submit to the official GLUE and SuperGLUE benchmark evaluation servers.

If you wish to run (I guess this is what you want) on the `dev` set of the `RTE` task, you can pass `rte/validation` instead of `dev.tsv`. And yes, the `huggingface/datasets` automatically fetches, caches, and loads the dataset by its name.
If you want to load a custom dataset (that cannot be found in https://huggingface.co/datasets/viewer/) you can still create a package for that particular dataset, see: https://huggingface.co/docs/datasets/add_dataset.html

**Comment by dqxiu** [comment]
Thanks so much💕!
